services:
  postgres:
    container_name:
    image:
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA:
    volumes:
      -
    ports:
      -
    networks:
      -
    restart:

  rabbitmq:
    container_name:
    image:
    volumes:
      -
    ports:
      -
      -
    networks:
      -
    restart:


networks:
  postgres:
    driver:


volumes:
  postgres:
  rabbitmq: