create table binary_content (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id int8 not null,
    type_file varchar(255) not null,
    file_as_array_of_bytes bytea not null
);

create table app_document (
    id                int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name          varchar(255) not null,
    file_size         int8 not null,
    mime_type         varchar(255) not null,
    telegram_file_id  varchar(255) not null
);

create table app_photo (
    id                int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_size         int4 not null ,
    telegram_file_id  varchar(255) not null
);

create table application_user (
    id               int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id          varchar(255) not null ,
    email            varchar(255) unique ,
    first_login_date timestamp,
    first_name       varchar(255),
    is_active        boolean,
    last_name        varchar(255),
    telegram_user_id int8,
    user_name        varchar(255),
    user_state       varchar(255)
);



create table message_entity (
    id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update jsonb not null
);

