create table top_250_films (
                           id                int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_film  varchar(30) not null unique
);
create table top_250_series (
                               id                int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               id_series  varchar(30) not null unique
);